package DCIS;

import java.awt.Toolkit;
import java.sql.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author shime
 */
public class AllApointments extends javax.swing.JDialog {

Connection con=ConnectionDB.ConnectDb();  
PreparedStatement pst=null;
ResultSet rs=null;
public AllApointments(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        searchAppt();
        setTitle("DCIS - Search Result Appointments");
        setIconImage(Toolkit.getDefaultToolkit().getImage(Admin_DB.class.getResource("/DCIS/photo_2018-12-09_15-04-39.jpg")));
  
    }
 public AllApointments() {
       initComponents();
        searchAppt();
        setTitle("DCIS - Search Result Appointments");
        setIconImage(Toolkit.getDefaultToolkit().getImage(Admin_DB.class.getResource("/DCIS/photo_2018-12-09_15-04-39.jpg")));
  
    }
 /*
 public void refresh(){
     try{
         String sql="SELECT * FROM viewtodayappointments";
                pst=con.prepareStatement(sql);
                pst.setString(1,Appointments.patientMRN);
             
                rs=pst.executeQuery();
                tblAllAppts.setModel(DbUtils.resultSetToTableModel(rs));
    }              
    catch(Exception e){
        
    }
 }
 */
 
 /*refresh updated;*/

   public  void refreshUpdated(ResultSet r){
		  
	tblAllAppts.setModel(DbUtils.resultSetToTableModel(r));
	}

public void searchAppt(){
    try{
         String sql="SELECT * FROM viewtodayappointments WHERE PatientMRN=?";
                pst=con.prepareStatement(sql);
                pst.setString(1,Appointments.patientMRN);
             
                rs=pst.executeQuery();
                tblAllAppts.setModel(DbUtils.resultSetToTableModel(rs));
    }              
    catch(Exception e){
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllAppts = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tblAllAppts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAllAppts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "MRN", "Dentist Name", "Appointment Time", "Appointment Date", "Appointment Service"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAllAppts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllApptsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAllAppts);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblAllApptsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllApptsMouseClicked
      //update appointment
     try{
              int row= tblAllAppts.getSelectedRow();
          String id= tblAllAppts.getModel().getValueAt(row, 0).toString();
       String sql= "SELECT AppointmentID,AppointmentDate,AppointmentTime FROM appointment WHERE appointmentid=?";
       
            pst=con.prepareStatement(sql);
            pst.setString(1, id);
            
            rs=pst.executeQuery();
             
            while(rs.next()){
              Date date=rs.getDate("AppointmentDate");
              Time time=rs.getTime("AppointmentTime");
              String appid=rs.getString("AppointmentID");
              
 UpdateAppointment upappt = new UpdateAppointment(new AllApointments(),true,date,time,appid);
 upappt.setVisible(true);   
  }
           
      
    }
    catch(Exception e){
       }
    }//GEN-LAST:event_tblAllApptsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllApointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllApointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllApointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllApointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new javax.swing.JFrame(), true
                new AllApointments(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAllAppts;
    // End of variables declaration//GEN-END:variables
}
