package DCIS;

import java.awt.Toolkit;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author shime
 */
 //public class ChangePassword extends javax.swing.JFrame {
   public class ChangePassword extends javax.swing.JDialog {
Connection con=ConnectionDB.ConnectDb();  
PreparedStatement pst=null;
ResultSet rs=null;
String currentPw;
public ChangePassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); 
        setUsername();
        setIconImage(Toolkit.getDefaultToolkit().getImage(Admin_DB.class.getResource("/DCIS/photo_2018-12-09_15-04-39.jpg")));
    
}
 public ChangePassword() {
      
        initComponents(); 
        setUsername();
        setIconImage(Toolkit.getDefaultToolkit().getImage(Admin_DB.class.getResource("/DCIS/photo_2018-12-09_15-04-39.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        panel_3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        oldPw = new javax.swing.JPasswordField();
        newPw = new javax.swing.JPasswordField();
        lblUn = new javax.swing.JLabel();
        lblOP = new javax.swing.JLabel();
        lblNP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        panel.setBackground(new java.awt.Color(153, 153, 153));

        panel_3.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Change Password", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 300, 30));

        btnCancel.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 130, 40));

        btnChange.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        jPanel2.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 110, 40));

        oldPw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(oldPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 300, 30));

        newPw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPwActionPerformed(evt);
            }
        });
        jPanel2.add(newPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 300, 30));

        lblUn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUn.setForeground(new java.awt.Color(255, 255, 255));
        lblUn.setText("Username");
        lblUn.setToolTipText("");
        jPanel2.add(lblUn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 100, 30));

        lblOP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOP.setForeground(new java.awt.Color(255, 255, 255));
        lblOP.setText("current password");
        lblOP.setToolTipText("");
        jPanel2.add(lblOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 160, 30));

        lblNP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNP.setForeground(new java.awt.Color(255, 255, 255));
        lblNP.setText("New Password");
        lblNP.setToolTipText("");
        jPanel2.add(lblNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, 30));

        javax.swing.GroupLayout panel_3Layout = new javax.swing.GroupLayout(panel_3);
        panel_3.setLayout(panel_3Layout);
        panel_3Layout.setHorizontalGroup(
            panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_3Layout.setVerticalGroup(
            panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
      changePassword();
         
    }//GEN-LAST:event_btnChangeActionPerformed
 public final void setUsername(){
     String username=Login.usernameHandler;
     txtUsername.setText(username);
 }
    public void changePassword(){
       try{
        String query="SELECT Password FROM useraccount WHERE Username=?"; 
        pst=con.prepareStatement(query); 
        pst.setString(1,txtUsername.getText()); 
        rs=pst.executeQuery();
        if (rs.next()){
            currentPw=rs.getString("Password");
        }
         //JOptionPane.showMessageDialog(null,currentPw); to check if the system gets the current password
        if(currentPw.equals(oldPw.getText())){
    String sql="UPDATE useraccount SET Password=? WHERE Username=? AND Password=?";
    pst=con.prepareStatement(sql);
    pst.setString(1,newPw.getText());
    pst.setString(2,txtUsername.getText());
    pst.setString(3,oldPw.getText());
    pst.executeUpdate();
    
     JOptionPane.showMessageDialog(null,"You have changer your password succesfully.");
     dispose();
          }
         else{
             JOptionPane.showMessageDialog(null,"Please enter your current password correctly. ","Error",JOptionPane.ERROR_MESSAGE);
             oldPw.setText("");
             oldPw.grabFocus();
        }
     } 
         catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
            }        
 }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
     dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void newPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNP;
    private javax.swing.JLabel lblOP;
    private javax.swing.JLabel lblUn;
    private javax.swing.JPasswordField newPw;
    private javax.swing.JPasswordField oldPw;
    private javax.swing.JPanel panel;
    public javax.swing.JPanel panel_3;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
